## **1. Basic Array Manipulation:**

In [2]:
import numpy as np
np_array = np.arange(10)
np_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##  Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [10]:
array_1d = np.arange(9)
array_3x3 = array_1d.reshape(3, 3)

print(array_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#   Access the element at the second row, second column

In [11]:
array_1d = np.arange(10)
array_5x2 = array_1d.reshape(5, 2)

element = array_5x2[1, 1]

print("Element at the second row, second column:", element)


Element at the second row, second column: 3


## Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].

In [13]:
array1 = np.array([2, 4, 6])
array2 = np.array([4, 5, 6])

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
division_result = array1 / array2

print("Element-wise addition:", addition_result)
print("Element-wise subtraction:", subtraction_result)
print("Element-wise multiplication:", multiplication_result)
print("Element-wise division:", division_result)


Element-wise addition: [ 6  9 12]
Element-wise subtraction: [-2 -1  0]
Element-wise multiplication: [ 8 20 36]
Element-wise division: [0.5 0.8 1. ]


#  Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].

In [14]:
array = np.array([1, 2, 3, 4, 5])

array_sum = np.sum(array)
array_mean = np.mean(array)
array_stddev = np.std(array)

print("Sum of the array:", array_sum)
print("Mean of the array:", array_mean)
print("Standard deviation of the array:", array_stddev)


Sum of the array: 15
Mean of the array: 3.0
Standard deviation of the array: 1.4142135623730951


##  Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = np_array.reshape(2, 3)

reshaped_array


array([[1, 2, 3],
       [4, 5, 6]])

##  **2. Indexing and Slicing:**

## Create a 5x5 array with random integers.

In [18]:
random_array = np.random.randint(0, 101, size=(5, 5))

random_array



array([[96,  3, 73, 18, 88],
       [38, 61, 47, 81,  3],
       [ 9, 54, 71, 63, 68],
       [82, 42, 72, 74, 73],
       [58, 77,  4, 75, 72]])

# Replace all values in the sub-array with a specific value.

In [27]:
random_array = np.random.randint(0, 100, size=(5, 5))

print("Original array:")
print(random_array)

random_array[0:1, 0:4] = 99
print("\nArray after replacing values in the sub-array:")
print(random_array)



Original array:
[[72 45 76 47 69]
 [18  1 62  4 21]
 [65 96 85 87 73]
 [27 30 51 34 76]
 [15 56  1 16  1]]

Array after replacing values in the sub-array:
[[99 99 99 99 69]
 [18  1 62  4 21]
 [65 96 85 87 73]
 [27 30 51 34 76]
 [15 56  1 16  1]]


## Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [30]:
array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
subarray = array[[1, 3], :]

subarray


array([[3, 4],
       [7, 8]])

##  **3. Broadcasting:**

## Create a 2D array of shape (3, 3) with values from 0 to 2.

In [31]:
np_array = np.tile(np.arange(3), (3, 1))

np_array


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

## Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [35]:
array_2d = np.array([[0, 1, 2], [0, 1, 2], [0, 1, 2]])
array_1d = np.array([1, 2, 3])
add_array = array_2d + array_1d

print("2D array:")
print(array_2d)
print("\n1D array:")
print(array_1d)
print("\nResult after broadcasting:")
add_array


2D array:
[[0 1 2]
 [0 1 2]
 [0 1 2]]

1D array:
[1 2 3]

Result after broadcasting:


array([[1, 3, 5],
       [1, 3, 5],
       [1, 3, 5]])

#  **4. Concatenation and Splitting**

# 1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.

In [38]:
array1 = np.random.randint(10, size=(3, 3))
array2 = np.random.randint(10, size=(3, 3))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
concatenated_horizontal = np.concatenate((array1, array2), axis=1)
concatenated_vertical = np.concatenate((array1, array2), axis=0)
print("Concatenated horizontally:\n", concatenated_horizontal)
print("Concatenated vertically:\n", concatenated_vertical)

first_half = concatenated_horizontal[:, :array1.shape[1]]
second_half = concatenated_horizontal[:, array1.shape[1]:]
top_half = concatenated_vertical[:array1.shape[0], :]
bottom_half = concatenated_vertical[array1.shape[0]:, :]

print("Split from concatenated horizontal (assuming original shapes are known):")
print("First half:\n", first_half)
print("Second half:\n", second_half)

print("Split from concatenated vertical (assuming original shapes are known):")
print("Top half:\n", top_half)
print("Bottom half:\n", bottom_half)


Array 1:
 [[2 9 7]
 [5 4 3]
 [8 1 4]]
Array 2:
 [[4 9 1]
 [3 2 1]
 [7 3 4]]
Concatenated horizontally:
 [[2 9 7 4 9 1]
 [5 4 3 3 2 1]
 [8 1 4 7 3 4]]
Concatenated vertically:
 [[2 9 7]
 [5 4 3]
 [8 1 4]
 [4 9 1]
 [3 2 1]
 [7 3 4]]
Split from concatenated horizontal (assuming original shapes are known):
First half:
 [[2 9 7]
 [5 4 3]
 [8 1 4]]
Second half:
 [[4 9 1]
 [3 2 1]
 [7 3 4]]
Split from concatenated vertical (assuming original shapes are known):
Top half:
 [[2 9 7]
 [5 4 3]
 [8 1 4]]
Bottom half:
 [[4 9 1]
 [3 2 1]
 [7 3 4]]


## Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also oploop

In [41]:
# Initialize a dictionary to store counts for each number
number_counts = {}
for number in [1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5]:
  if number in number_counts:
    number_counts[number] += 1 
  else:
    number_counts[number] = 1 
mode = max(number_counts, key=number_counts.get)
print("The mode of the array is:", mode)


The mode of the array is: 1
